// 'use server'
import { KYCProvider } from "@/context/KYCContext";
import { cookies } from 'next/headers'; // Import cookies utility from Next.js
import { redirect } from 'next/navigation'; // Import redirect utility from Next.js

export const metadata = {
  title: 'KYC FORM',
  description: 'Generated by Next.js',
}

export default function KycLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Check for the token in cookies
  const cookieStore = cookies();
  const token = cookieStore.get('token'); // Replace 'token' with the actual name of your token cookie

  // Redirect to login page if token is not present
  if (!token) {
    redirect('/login'); // Adjust the path to your login page
  }

  return (
    <html lang="en">
      <body>
        <KYCProvider>
          {children}
        </KYCProvider>
      </body>
    </html>
  );
}
